insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (1, 'Smartphone Car Mount with Wireless Charging', 'Phone Accessories', 39.99, 52, 5, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (2, 'Breezy Off-The-Shoulder Top', 'Women''s Tops', 34.99, 75, 4, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (3, 'Fruit and Nut Medley', 'Nuts and Trail Mix', 5.99, 92, 3, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (4, 'Eco-Friendly Yoga Mat', 'Sustainable Fitness Equipment', 39.99, 58, 1, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (5, 'Magnetic Whiteboard', 'Office Supplies', 34.99, 75, 1, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (6, 'Kids'' Trampoline', 'Outdoor Activity Toys', 139.99, 24, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (7, 'Lightweight Backpacking Tent', 'Camping Equipment', 129.99, 80, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (8, 'Herb Seasoned Rice', 'Rice', 2.99, 62, 3, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (9, 'Stylish Combat Boots', 'Footwear - Boots', 99.99, 100, 2, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (10, 'Electric Stir Fry Pan', 'Cooking Appliances', 49.99, 91, 1, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (11, 'Beach Cover-Up', 'Swimwear Accessories', 29.99, 11, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (12, 'Kids'' Activity Book', 'Children''s Educational Books', 14.99, 50, 2, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (13, 'Electric Pressure Cooker', 'Small Appliances', 89.99, 89, 5, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (14, 'Stuffed Peppers with Quinoa', 'Vegetarian Meals', 7.99, 90, 4, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (15, 'Coconut Cream Pie', 'Desserts', 9.49, 41, 2, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (16, 'Chili Lime Shrimp', 'Marinated Seafood', 8.99, 13, 4, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (17, 'Casual Long Cardigan', 'Knitwear', 45.99, 65, 1, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (18, 'Electric Rice Cooker', 'Cooking Appliances', 39.99, 11, 3, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (19, 'Organic Granola', 'Healthy Breakfast Options', 5.49, 30, 5, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (20, 'Steak Seasoning Rub', 'Rubs and Seasonings', 2.49, 68, 4, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (21, 'Party Mini Dress', 'Cocktail Dresses', 69.99, 94, 1, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (22, 'Wine Glasses', 'Kitchen Accessories', 29.99, 58, 1, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (23, 'Chili Beans (canned)', 'Canned Vegetables', 1.69, 15, 1, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (24, 'Olive Oil', 'Cooking Oils', 7.99, 9, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (25, 'Stainless Steel Mixing Bowls', 'Cookware', 29.99, 100, 2, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (26, 'Fitness Jump Rope with LCD Counter', 'Cardio Equipment', 15.99, 29, 5, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (27, 'Printed Maxi Skirt', 'Skirts', 39.99, 13, 5, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (28, 'Mango Sticky Rice Dessert', 'Asian Desserts', 4.5, 27, 2, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (29, 'Personalized Keychain', 'Custom Accessories', 10.99, 83, 3, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (30, 'Magnetic Spice Jars', 'Kitchen Storage & Organization', 24.99, 92, 3, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (31, 'Floral Summer Dress', 'Casual Dresses', 39.99, 73, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (32, 'Smart Thermostat', 'Home Automation', 149.99, 45, 1, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (33, 'Peanut Butter Banana Smoothie', ' smoothies', 3.99, 21, 1, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (34, 'Professional Chef Knife', 'Cutlery', 89.99, 37, 4, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (35, 'Smartphone Tripod with Bluetooth Remote', 'Smartphone Accessories', 29.99, 28, 2, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (36, 'Insulated Lunch Bag', 'Food Storage Solutions', 24.99, 70, 1, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (37, 'Honey Roasted Peanuts', 'Nuts and Seeds', 3.19, 24, 5, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (38, 'Digital Alarm Clock', 'Smart Home & Security', 19.99, 72, 5, 5);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (39, 'Hydration Backpack', 'Outdoor Accessories', 39.99, 35, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (40, 'Roasted Garlic Aioli', 'Dips', 3.79, 84, 5, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (41, 'Baked Falafel', 'Snacks', 5.49, 12, 2, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (42, 'Chiffon Blouse', 'Dress Shirts', 39.99, 13, 1, 2);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (43, 'Memory Foam Mattress Pad', 'Bedding & Linens', 69.99, 89, 1, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (44, 'Dark Chocolate Tart', 'Chocolate Desserts', 6.29, 66, 3, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (45, 'Raisin Cinnamon Granola', 'Granola', 3.79, 99, 2, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (46, 'Classic Pumps', 'Women''s Dress Shoes', 64.99, 96, 1, 4);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (47, 'Magic Color-Changing Mug', 'Drinkware', 14.99, 81, 4, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (48, 'Stuffed Peppers with Quinoa', 'Vegetarian Meals', 7.99, 79, 4, 1);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (49, 'Quinoa Salad', 'Ready-to-Eat Meals', 5.99, 39, 3, 3);
insert into producto (id_producto, nombre, descripcion, precio_unitario, stock, id_categoria, id_proveedor) values (50, 'Garlic Butter Shrimp', 'Frozen Seafood', 8.99, 51, 5, 1);
